title: Team Macuga
url: https://teammacuga.com
baseurl: ""        # IMPORTANT: empty for a custom domain at the root

theme: null
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag

defaults:
  - scope: { path: "" }
    values:
      layout: default

collections:
  products:
    output: true
    permalink: /shop/:slug/

shopify:
  domain: yourshop.myshopify.com
