title: Team Macuga
tagline: Four siblings — one dream.
url: "https://smacuga217.github.io"
baseurl: "/TeamMacuga"

# Use our own layout/includes instead of Primer’s
theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-paginate
