title: Team Macuga
url: "https://smacuga217.github.io"
baseurl: "/TeamMacuga"   # <- important for GitHub Pages
theme: null
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag

defaults:
  - scope: { path: "" }
    values:
      layout: default
