name: Fetch FIS latest results

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install beautifulsoup4 requests pyyaml
      - run: python scripts/fetch_fis.py
      - name: Commit updated data
        run: |
          if [[ -n "$(git status --porcelain _data/results_auto.yml)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add _data/results_auto.yml
            git commit -m "chore(data): auto-update results from FIS"
            git push
          else
            echo "No changes."
          fi
