name: Fetch FIS results
on:
  schedule:
    - cron: "23 6 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install Playwright
        run: |
          pip install playwright
          python -m playwright install --with-deps chromium
      - name: Run scraper
        run: python scripts/fetch_fis_results.py
      - name: Commit JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add assets/data/fis_results.json
          git commit -m "chore: update FIS results" || echo "No changes"
          git push
