name: Fetch news

on:
  schedule:
    - cron: '13 5 * * *'   # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 lxml

      - name: Run fetcher
        run: python scripts/fetch_news.py

      - name: Commit changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _data/news_feed.json
          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi
          git commit -m "chore(news): update feed [skip ci]"
          git push
