# .github/workflows/news.yml
name: Fetch news
on:
  schedule:
    - cron: '13 5 * * *'   # daily
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install feedparser requests
      - run: python scripts/fetch_news.py
      - name: Commit & push
        run: |
          git config user.name "automation"
          git config user.email "actions@users.noreply.github.com"
          git add _data/news_feed.json
          git diff --cached --quiet || git commit -m "chore: update news feed"
          git push
