name: Update FIS Results
on:
  schedule:
    - cron: '0 */12 * * *'   # every 12 hours
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Run scraper
        run: |
          pip install pyyaml
          python scripts/fis_scrape.py
      - name: Commit & push data
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add _data/results.yml
            git commit -m "chore(results): auto-update from FIS"
            git push
          else
            echo "No changes."
